# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulator.proto',
  package='simulator',
  syntax='proto3',
  serialized_pb=_b('\n\x0fsimulator.proto\x12\tsimulator\"\x0b\n\tVoidValue\"U\n\x05\x41ngle\x12\"\n\x04kind\x18\x01 \x01(\x0e\x32\x14.simulator.JointKind\x12\x0c\n\x04roll\x18\x02 \x01(\x02\x12\r\n\x05pitch\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\"O\n\x08Position\x12\"\n\x04kind\x18\x01 \x01(\x0e\x32\x14.simulator.PartsKind\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02*\xae\x01\n\tJointKind\x12\x12\n\x0eRIGHT_SHOULDER\x10\x00\x12\x0f\n\x0bRIGHT_ELBOW\x10\x01\x12\r\n\tRIGHT_HIP\x10\x03\x12\x0e\n\nRIGHT_KNEE\x10\x04\x12\x0e\n\nRIGHT_FOOT\x10\x05\x12\x11\n\rLEFT_SHOULDER\x10\x06\x12\x0e\n\nLEFT_ELBOW\x10\x07\x12\x0c\n\x08LEFT_HIP\x10\t\x12\r\n\tLEFT_KNEE\x10\n\x12\r\n\tLEFT_FOOT\x10\x0b*\x15\n\tPartsKind\x12\x08\n\x04HEAD\x10\x00\x32\xa2\x01\n\tSimulator\x12\x33\n\x05Start\x12\x14.simulator.VoidValue\x1a\x14.simulator.VoidValue\x12-\n\x04Send\x12\x10.simulator.Angle\x1a\x13.simulator.Position\x12\x31\n\x03\x45nd\x12\x14.simulator.VoidValue\x1a\x14.simulator.VoidValueb\x06proto3')
)

_JOINTKIND = _descriptor.EnumDescriptor(
  name='JointKind',
  full_name='simulator.JointKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RIGHT_SHOULDER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_ELBOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_HIP', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_KNEE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_FOOT', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_SHOULDER', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_ELBOW', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_HIP', index=7, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_KNEE', index=8, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_FOOT', index=9, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=212,
  serialized_end=386,
)
_sym_db.RegisterEnumDescriptor(_JOINTKIND)

JointKind = enum_type_wrapper.EnumTypeWrapper(_JOINTKIND)
_PARTSKIND = _descriptor.EnumDescriptor(
  name='PartsKind',
  full_name='simulator.PartsKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEAD', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=388,
  serialized_end=409,
)
_sym_db.RegisterEnumDescriptor(_PARTSKIND)

PartsKind = enum_type_wrapper.EnumTypeWrapper(_PARTSKIND)
RIGHT_SHOULDER = 0
RIGHT_ELBOW = 1
RIGHT_HIP = 3
RIGHT_KNEE = 4
RIGHT_FOOT = 5
LEFT_SHOULDER = 6
LEFT_ELBOW = 7
LEFT_HIP = 9
LEFT_KNEE = 10
LEFT_FOOT = 11
HEAD = 0



_VOIDVALUE = _descriptor.Descriptor(
  name='VoidValue',
  full_name='simulator.VoidValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=41,
)


_ANGLE = _descriptor.Descriptor(
  name='Angle',
  full_name='simulator.Angle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='simulator.Angle.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='simulator.Angle.roll', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='simulator.Angle.pitch', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='simulator.Angle.yaw', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=128,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='simulator.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='simulator.Position.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='simulator.Position.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='simulator.Position.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='simulator.Position.z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=209,
)

_ANGLE.fields_by_name['kind'].enum_type = _JOINTKIND
_POSITION.fields_by_name['kind'].enum_type = _PARTSKIND
DESCRIPTOR.message_types_by_name['VoidValue'] = _VOIDVALUE
DESCRIPTOR.message_types_by_name['Angle'] = _ANGLE
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.enum_types_by_name['JointKind'] = _JOINTKIND
DESCRIPTOR.enum_types_by_name['PartsKind'] = _PARTSKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoidValue = _reflection.GeneratedProtocolMessageType('VoidValue', (_message.Message,), dict(
  DESCRIPTOR = _VOIDVALUE,
  __module__ = 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:simulator.VoidValue)
  ))
_sym_db.RegisterMessage(VoidValue)

Angle = _reflection.GeneratedProtocolMessageType('Angle', (_message.Message,), dict(
  DESCRIPTOR = _ANGLE,
  __module__ = 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:simulator.Angle)
  ))
_sym_db.RegisterMessage(Angle)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:simulator.Position)
  ))
_sym_db.RegisterMessage(Position)



_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='simulator.Simulator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=412,
  serialized_end=574,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='simulator.Simulator.Start',
    index=0,
    containing_service=None,
    input_type=_VOIDVALUE,
    output_type=_VOIDVALUE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='simulator.Simulator.Send',
    index=1,
    containing_service=None,
    input_type=_ANGLE,
    output_type=_POSITION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='End',
    full_name='simulator.Simulator.End',
    index=2,
    containing_service=None,
    input_type=_VOIDVALUE,
    output_type=_VOIDVALUE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
